language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t piyuesh/docker-test -f Dockerfile.dev .

script:
  - docker run -e CI=true piyuesh/docker-test npm run test -- --coverage